In [1]:
import pandas as pd
from datasets import load_dataset

pd.set_option("display.max_colwidth", 300)

ds = load_dataset("pyupeu/social-media-peruvian-sentiment")

df_all = pd.concat(
    [ds[split].to_pandas().assign(split_original=split) for split in ds.keys()],
    ignore_index=True
)

print("Total de registros en el pool unificado:", len(df_all))
print(df_all["split_original"].value_counts())
df_all.head()

README.md:   0%|          | 0.00/857 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  990kB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/validation-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  306kB

data/validation-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  255kB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/9336 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2918 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2335 [00:00<?, ? examples/s]

Total de registros en el pool unificado: 14589
split_original
train         9336
validation    2918
test          2335
Name: count, dtype: int64

,text,label,label_name,split_original
0,"Salió para Aser farándula ese chato, solo quiere llamar la atención 😂 q trabaje bago , aragán",0,negative,train
1,Si así eres tu también!!! ... Cuando llegaste a Cancun al hotel donde trabajaba.. Y la netta casi todos son bien mamones.. Y otros mamones y piojos jajaj pero bueno en sus videos son otra cosa👎🏻,0,negative,train
2,Nunca se tiene pocos zapatos... 🤣 🤣 🤣 🤣 Tengo algunos tacones y botas que aun no los e usado y sigo comprando mas.,1,neutral,train
3,Queen Reigne te 😂😂😂 sorry na,1,neutral,train
4,En media hora comienza el toque de queda dijo,1,neutral,train

## Eliminar textos con etiquetas contraadictorias

In [2]:
# Identificar textos duplicados (en cualquier split) con más de una etiqueta distinta
revision_duplicados = (
    df_all[df_all["text"].duplicated(keep=False)]
    .groupby("text")
    .agg(
        cantidad=("text", "count"),
        etiquetas=("label_name", lambda x: sorted(set(x))),
        splits=("split_original", lambda x: sorted(set(x)))
    )
    .reset_index()
)

revision_duplicados["num_etiquetas"] = revision_duplicados["etiquetas"].apply(len)

textos_contradictorios = revision_duplicados[
    revision_duplicados["num_etiquetas"] > 1
]["text"].tolist()

print("Textos con etiquetas contradictorias encontrados:", len(textos_contradictorios))

df_sin_contradicciones = df_all[~df_all["text"].isin(textos_contradictorios)].copy()

print("Antes:", len(df_all))
print("Después de eliminar contradictorios:", len(df_sin_contradicciones))

Textos con etiquetas contradictorias encontrados: 3
Antes: 14589
Después de eliminar contradictorios: 14583

## Eliminar duplicados simples, nos quedamos con una sola ocurrencia por texto único

In [3]:
duplicados_restantes_antes = df_sin_contradicciones["text"].duplicated().sum()
print("Duplicados restantes antes de deduplicar:", duplicados_restantes_antes)

df_clean = (
    df_sin_contradicciones
    .drop_duplicates(subset=["text"], keep="first")
    .reset_index(drop=True)
)

print("Antes de deduplicar:", len(df_sin_contradicciones))
print("Después de deduplicar:", len(df_clean))
print("Duplicados restantes:", df_clean["text"].duplicated().sum())

Duplicados restantes antes de deduplicar: 39
Antes de deduplicar: 14583
Después de deduplicar: 14544
Duplicados restantes: 0

## Limpiar URLs y el símbolo # de hashtags (se conservan menciones). Además las tildes se mantienen

In [5]:
import re

def limpiar_urls_hashtags_conservando_menciones(text):
    if not isinstance(text, str):
        return ""

    # 1. Eliminar URLs reales
    text = re.sub(r"http\S+|www\.\S+|https?://\S+", " ", text, flags=re.IGNORECASE)

    # 2. Hashtags: quitar el símbolo # pero conservar la palabra
    text = re.sub(r"#(\w+)", r"\1", text)

    # 3. Normalizar espacios
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_clean["text_clean"] = df_clean["text"].apply(limpiar_urls_hashtags_conservando_menciones)

# Verificamos que ya no queden URLs ni hashtags con #
patron_url_real = r"(?:http\S+|www\.\S+|https?://\S+)"
patron_hashtag = r"#\w+"
patron_mencion = r"@\w+"

print("URLs reales restantes:", df_clean["text_clean"].str.contains(patron_url_real, regex=True, case=False, na=False).sum())
print("Hashtags con # restantes:", df_clean["text_clean"].str.contains(patron_hashtag, regex=True, na=False).sum())
print("Menciones restantes:", df_clean["text_clean"].str.contains(patron_mencion, regex=True, na=False).sum())

URLs reales restantes: 0
Hashtags con # restantes: 0
Menciones restantes: 56

In [6]:
import re

# Ver una muestra de los textos con mención, tal cual quedaron
con_mencion = df_clean[df_clean["text_clean"].str.contains(r"@\w+", regex=True, na=False)]
print("Total de registros con mención:", len(con_mencion))

con_mencion[["text", "text_clean", "label_name"]].head(20)

Total de registros con mención: 56

,text,text_clean,label_name
28,"Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto","Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto",negative
787,Parece que la Shakira se puso doble to@ll@ higiénic@... Ya vuelta... 😎😎😎,Parece que la Shakira se puso doble to@ll@ higiénic@... Ya vuelta... 😎😎😎,neutral
1029,"¶Hace 45 años, nuestro 🇵🇪#PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA Judí...","¶Hace 45 años, nuestro 🇵🇪PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA JudíoEs...",negative
1454,"No cambias cabrilla, más palo eres chtm, !Yo me rectifió cuando me dé la gana! siiiiiii, toda una macinon@ tira mi3rd4, se te encogieron las boloñ@s 😬😬😂😂😂 aprovecha mientras tengas vitrina trde o temprano se te acabará o por viej@ ó porque ya no vendes con tus dices seguidores que tambien se hac...","No cambias cabrilla, más palo eres chtm, !Yo me rectifió cuando me dé la gana! siiiiiii, toda una macinon@ tira mi3rd4, se te encogieron las boloñ@s 😬😬😂😂😂 aprovecha mientras tengas vitrina trde o temprano se te acabará o por viej@ ó porque ya no vendes con tus dices seguidores que tambien se hac...",negative
1703,Buena la ensalada y felicidades para l@s héroes urban@s👏👏👏👏,Buena la ensalada y felicidades para l@s héroes urban@s👏👏👏👏,positive
2031,"Rojos izquierdistas y la Derecha corrupt@s la cras, pode dumbres de la politica peruana, venden humo, zangan@s, mermeler@s vividores de la teta del estado son la corruptela vendid@s al mejor postor junto a su mami chica k, fujiapristas, vitochos, etc, etc corrupt@s siguen vendiendo humo se creen...","Rojos izquierdistas y la Derecha corrupt@s la cras, pode dumbres de la politica peruana, venden humo, zangan@s, mermeler@s vividores de la teta del estado son la corruptela vendid@s al mejor postor junto a su mami chica k, fujiapristas, vitochos, etc, etc corrupt@s siguen vendiendo humo se creen...",negative
3237,"No tiene ni para tr@g@r, encima propicia la compra de celulares Hurtados, la firme chino le haces un mal a ese gordo llevandolo contigo! 🤦🏻‍♂️","No tiene ni para tr@g@r, encima propicia la compra de celulares Hurtados, la firme chino le haces un mal a ese gordo llevandolo contigo! 🤦🏻‍♂️",negative
3376,"Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total","Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total",negative
3456,"Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻","Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻",neutral
3593,"Veo muchas madres identificadas, pero nadie piensa en los hermanos mayores. Nosotr@s también somos parte del calvario 😂✨","Veo muchas madres identificadas, pero nadie piensa en los hermanos mayores. Nosotr@s también somos parte del calvario 😂✨",negative
3687,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,positive
4260,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es #Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,negative
4731,"Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! #MASMUSICACONMARSHALL in one 🌎","Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! MASMUSICACONMARSHALL in one 🌎",positive
4957,"Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍","Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍",positive
5495,La gente se cree muy digna y correcta por aca ... Aprovechan en escribir cualquier cosa por que nadie les sabe sus porquerias... Pur@s in.felices kchu dasas y kchu dos y pend.ejas y pendejos vallan a vivir sus vidas basu ras jajajajaja 🤣,La gente se cree muy digna y correcta por aca ... Aprovechan en escribir cualquier cosa por que nadie les sabe sus porquerias... Pur@s in.felices kchu dasas y kchu dos y pend.ejas y pendejos vallan a vivir sus vidas basu ras jajajajaja 🤣,negative
5510,@Un tombo pasó por ahí en una moto deportiva 🤣,@Un tombo pasó por ahí en una moto deportiva 🤣,neutral
5670,"Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de #Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una rec...","Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una reconoc...",negative
5928,@asistenciaestudioespinozaramos ya fuiste 🤣🤣🤣,@asistenciaestudioespinozaramos ya fuiste 🤣🤣🤣,negative
6218,con ese cuerpazo l@s envidios@s no paran de rajar😁,con ese cuerpazo l@s envidios@s no paran de rajar😁,negative
6743,"Así, nosotras las seguidoras también disfrutamos de los paisajes de todos los países y de nuestro rico Perú, es una idea que me imagino que todas están de acuerdo, x que salir en mancha es mas chevere, cosa que también chapamos taper y micro🤣🤣🤣, así también nosotras participamos en las aventur@s...","Así, nosotras las seguidoras también disfrutamos de los paisajes de todos los países y de nuestro rico Perú, es una idea que me imagino que todas están de acuerdo, x que salir en mancha es mas chevere, cosa que también chapamos taper y micro🤣🤣🤣, así también nosotras participamos en las aventur@s...",positive

In [7]:
# Separar cuáles son el placeholder "@username" y cuáles son otra cosa (posibles nombres reales)
es_placeholder = con_mencion["text_clean"].str.contains(r"@username\b", regex=True, na=False, case=False)

print("Con placeholder '@username':", es_placeholder.sum())
print("Con otro tipo de mención (revisar):", (~es_placeholder).sum())

con_mencion[~es_placeholder][["text", "text_clean", "label_name"]]

Con placeholder '@username': 0
Con otro tipo de mención (revisar): 56

,text,text_clean,label_name
28,"Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto","Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto",negative
787,Parece que la Shakira se puso doble to@ll@ higiénic@... Ya vuelta... 😎😎😎,Parece que la Shakira se puso doble to@ll@ higiénic@... Ya vuelta... 😎😎😎,neutral
1029,"¶Hace 45 años, nuestro 🇵🇪#PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA Judí...","¶Hace 45 años, nuestro 🇵🇪PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA JudíoEs...",negative
1454,"No cambias cabrilla, más palo eres chtm, !Yo me rectifió cuando me dé la gana! siiiiiii, toda una macinon@ tira mi3rd4, se te encogieron las boloñ@s 😬😬😂😂😂 aprovecha mientras tengas vitrina trde o temprano se te acabará o por viej@ ó porque ya no vendes con tus dices seguidores que tambien se hac...","No cambias cabrilla, más palo eres chtm, !Yo me rectifió cuando me dé la gana! siiiiiii, toda una macinon@ tira mi3rd4, se te encogieron las boloñ@s 😬😬😂😂😂 aprovecha mientras tengas vitrina trde o temprano se te acabará o por viej@ ó porque ya no vendes con tus dices seguidores que tambien se hac...",negative
1703,Buena la ensalada y felicidades para l@s héroes urban@s👏👏👏👏,Buena la ensalada y felicidades para l@s héroes urban@s👏👏👏👏,positive
2031,"Rojos izquierdistas y la Derecha corrupt@s la cras, pode dumbres de la politica peruana, venden humo, zangan@s, mermeler@s vividores de la teta del estado son la corruptela vendid@s al mejor postor junto a su mami chica k, fujiapristas, vitochos, etc, etc corrupt@s siguen vendiendo humo se creen...","Rojos izquierdistas y la Derecha corrupt@s la cras, pode dumbres de la politica peruana, venden humo, zangan@s, mermeler@s vividores de la teta del estado son la corruptela vendid@s al mejor postor junto a su mami chica k, fujiapristas, vitochos, etc, etc corrupt@s siguen vendiendo humo se creen...",negative
3237,"No tiene ni para tr@g@r, encima propicia la compra de celulares Hurtados, la firme chino le haces un mal a ese gordo llevandolo contigo! 🤦🏻‍♂️","No tiene ni para tr@g@r, encima propicia la compra de celulares Hurtados, la firme chino le haces un mal a ese gordo llevandolo contigo! 🤦🏻‍♂️",negative
3376,"Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total","Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total",negative
3456,"Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻","Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻",neutral
3593,"Veo muchas madres identificadas, pero nadie piensa en los hermanos mayores. Nosotr@s también somos parte del calvario 😂✨","Veo muchas madres identificadas, pero nadie piensa en los hermanos mayores. Nosotr@s también somos parte del calvario 😂✨",negative
3687,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,positive
4260,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es #Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,negative
4731,"Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! #MASMUSICACONMARSHALL in one 🌎","Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! MASMUSICACONMARSHALL in one 🌎",positive
4957,"Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍","Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍",positive
5495,La gente se cree muy digna y correcta por aca ... Aprovechan en escribir cualquier cosa por que nadie les sabe sus porquerias... Pur@s in.felices kchu dasas y kchu dos y pend.ejas y pendejos vallan a vivir sus vidas basu ras jajajajaja 🤣,La gente se cree muy digna y correcta por aca ... Aprovechan en escribir cualquier cosa por que nadie les sabe sus porquerias... Pur@s in.felices kchu dasas y kchu dos y pend.ejas y pendejos vallan a vivir sus vidas basu ras jajajajaja 🤣,negative
5510,@Un tombo pasó por ahí en una moto deportiva 🤣,@Un tombo pasó por ahí en una moto deportiva 🤣,neutral
5670,"Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de #Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una rec...","Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una reconoc...",negative
5928,@asistenciaestudioespinozaramos ya fuiste 🤣🤣🤣,@asistenciaestudioespinozaramos ya fuiste 🤣🤣🤣,negative
6218,con ese cuerpazo l@s envidios@s no paran de rajar😁,con ese cuerpazo l@s envidios@s no paran de rajar😁,negative
6743,"Así, nosotras las seguidoras también disfrutamos de los paisajes de todos los países y de nuestro rico Perú, es una idea que me imagino que todas están de acuerdo, x que salir en mancha es mas chevere, cosa que también chapamos taper y micro🤣🤣🤣, así también nosotras participamos en las aventur@s...","Así, nosotras las seguidoras también disfrutamos de los paisajes de todos los países y de nuestro rico Perú, es una idea que me imagino que todas están de acuerdo, x que salir en mancha es mas chevere, cosa que también chapamos taper y micro🤣🤣🤣, así también nosotras participamos en las aventur@s...",positive
6751,Escusas . Son pl@nas y punto jajaja😂,Escusas . Son pl@nas y punto jajaja😂,negative
6888,Todo es cortina de humo 💨... Magaly se tira un pedo y también es cortina de humo 🤦🏽‍♀️🤣🤣🤣 pobrecit@s,Todo es cortina de humo 💨... Magaly se tira un pedo y también es cortina de humo 🤦🏽‍♀️🤣🤣🤣 pobrecit@s,negative
6900,"Jajajjaja sigue env3ntando hu3vad@s nada te va resultar , dale con todo asta donde llegas prens@ chat@rr@😅👎😂 tarde k temprano vasa caer.","Jajajjaja sigue env3ntando hu3vad@s nada te va resultar , dale con todo asta donde llegas prens@ chat@rr@😅👎😂 tarde k temprano vasa caer.",negative
6962,"Tema: WARMISITAY Letra y Música: Milena Warthon, Franjo Artich Interprete: Milena Warthon Producción Musical: Franjo Artich Mezcla: Daniel Lujan Master: Francisco Holzmann Dirección audiovisual: Victor Vilchez ""Vedoble"" Producción: Warthon Records Coreografia: Mafe Martinez Esa pollerita roja ...","Tema: WARMISITAY Letra y Música: Milena Warthon, Franjo Artich Interprete: Milena Warthon Producción Musical: Franjo Artich Mezcla: Daniel Lujan Master: Francisco Holzmann Dirección audiovisual: Victor Vilchez ""Vedoble"" Producción: Warthon Records Coreografia: Mafe Martinez Esa pollerita roja mi...",neutral
7070,"Aaayyyy por Dios cómo se llenan la boca atacando la, quien sabe cómo fue su infancia y como superó todas las trabas que te pone la vida al no ser comprendida, nadie sabe, pero lo superó y ahora busca ayuda para con sus hijos y quién mejor que ella saber cómo ayudar a sus pequeños porque lamentab...","Aaayyyy por Dios cómo se llenan la boca atacando la, quien sabe cómo fue su infancia y como superó todas las trabas que te pone la vida al no ser comprendida, nadie sabe, pero lo superó y ahora busca ayuda para con sus hijos y quién mejor que ella saber cómo ayudar a sus pequeños porque lamentab...",negative
7096,Todo el PERU esta contigo @smulanovich 🇵🇪 Las redes de la corrupcion llegan a todos lados 😡 No te dejes pisar el poncho 💪,Todo el PERU esta contigo @smulanovich 🇵🇪 Las redes de la corrupcion llegan a todos lados 😡 No te dejes pisar el poncho 💪,negative
7210,SI Y OJALA QUE GANEN ASI BAJAN EL POLLO EL AZUCAR LOS FIDEOS EL PAN ETC ETC ETC ETC....POR ESO LOS DUEÑOS DEL PERUCHO LORCHOOOOO NOS AGARRAN DE TAR@DUPEDOS PORQUE CREEN QUE NO VEMOS MAS QUE PELOTA RODANDO...🤑😡🤑😡😡😡🤑🤪🤑🤑🤑😡😡😡,SI Y OJALA QUE GANEN ASI BAJAN EL POLLO EL AZUCAR LOS FIDEOS EL PAN ETC ETC ETC ETC....POR ESO LOS DUEÑOS DEL PERUCHO LORCHOOOOO NOS AGARRAN DE TAR@DUPEDOS PORQUE CREEN QUE NO VEMOS MAS QUE PELOTA RODANDO...🤑😡🤑😡😡😡🤑🤪🤑🤑🤑😡😡😡,negative
7805,Quisiera ganarla porque mi novio le encanta el fútbol es un jugadorazo pero de fútbol eh jejeje sería un lindo regalo para el participen amigos de este lindo premio te sigo como @med141923 Jorge Teves Taipe Mica Isabel Castillo Elena Lizárraga Con mucha fe bendiciones 😘,Quisiera ganarla porque mi novio le encanta el fútbol es un jugadorazo pero de fútbol eh jejeje sería un lindo regalo para el participen amigos de este lindo premio te sigo como @med141923 Jorge Teves Taipe Mica Isabel Castillo Elena Lizárraga Con mucha fe bendiciones 😘,positive
7830,"Sorry con ""ekiumi"", pero beto, luego de salir hablar decir y darle taaaantos minutos al tipejo este, no te queda la sensación de ser un poco como el otrora ""chuchi, chino""? En en serio? Tu vincha es harto conocida y llamar waripoler@s a los demás tbn, pero que no te ganen tus preferencias. La e...","Sorry con ""ekiumi"", pero beto, luego de salir hablar decir y darle taaaantos minutos al tipejo este, no te queda la sensación de ser un poco como el otrora ""chuchi, chino""? En en serio? Tu vincha es harto conocida y llamar waripoler@s a los demás tbn, pero que no te ganen tus preferencias. La es...",negative
7924,TODOS LOS QUE AMAMOS A NUESTRA PATRIA Y QUEREMOS QUE NO SIGA SIENDO DESTRUIDA Y SAQUEADA ECONOMIA POR LA ORGANIZACION CRIMINAL FILOT3RRORIST@CHAVIZTA QUE ESTA LLEVANDO AL DESPEÑADERO A NUESTRO PAÍS. OLVÍDENSE DEL COLOR POLÍTICO QUIEN SE APUNTA CON EL TRAILER YLOS PARLANTES PARA REVENTARLE LAS OR...,TODOS LOS QUE AMAMOS A NUESTRA PATRIA Y QUEREMOS QUE NO SIGA SIENDO DESTRUIDA Y SAQUEADA ECONOMIA POR LA ORGANIZACION CRIMINAL FILOT3RRORIST@CHAVIZTA QUE ESTA LLEVANDO AL DESPEÑADERO A NUESTRO PAÍS. OLVÍDENSE DEL COLOR POLÍTICO QUIEN SE APUNTA CON EL TRAILER YLOS PARLANTES PARA REVENTARLE LAS OR...,negative
7979,"Espero tener suerte ésta vez ✌🍀✌ Participen chic@s Gina Nancy Núñez, Sarita Ruiton, Edith Uquichi Ccana","Espero tener suerte ésta vez ✌🍀✌ Participen chic@s Gina Nancy Núñez, Sarita Ruiton, Edith Uquichi Ccana",neutral
8273,Viniendo de Yidda Eslava la película debe ser hermosa y divertida. Desde q ella empezó en combate mi hermana es fan de Yidda lloraba de felicidad por su embarazo cuando ganaba ect . Y desde allí yo también soy fan de Yidda porq demostró ser una luchadora y una exelente madre . Que bueno q Dios ...,Viniendo de Yidda Eslava la película debe ser hermosa y divertida. Desde q ella empezó en combate mi hermana es fan de Yidda lloraba de felicidad por su embarazo cuando ganaba ect . Y desde allí yo también soy fan de Yidda porq demostró ser una luchadora y una exelente madre . Que bueno q Dios t...,positive
8434,"Hermoso tema ,grande Susan!! Gracias Eva, el viejo y a N@thy por compartir!!!👏👏👏👏👏👏","Hermoso tema ,grande Susan!! Gracias Eva, el viejo y a N@thy por compartir!!!👏👏👏👏👏👏",positive
8646,"La gente son una cag...🤣🤣🤣,envidios@s de miércoles,hagan ejercicio y no traguen mucho psssss para k estén de regias cmo ella ...,pura envidia es..el vestido le queda ok👌❤️","La gente son una cag...🤣🤣🤣,envidios@s de miércoles,hagan ejercicio y no traguen mucho psssss para k estén de regias cmo ella ...,pura envidia es..el vestido le queda ok👌❤️",positive
8759,"Yo tengo que ganarme ese Canguro si o si , siganme para más recetas Huaralinas 😅😝❤️ @lahuaralina.pe","Yo tengo que ganarme ese Canguro si o si , siganme para más recetas Huaralinas 😅😝❤️ @lahuaralina.pe",positive
8947,"Muy bien @Maria Pia Copello, te felicito que las criticas te resbalen tu ponte lo quieras todo te queda hermoso y a las que no les gusta piña pues. Tu siempre seras la regia de regias. 😊😊😊👏👏👏👏👏👍💪💪💪💪🤩🤩🤩🥰🥰🥰🥰🥰","Muy bien @Maria Pia Copello, te felicito que las criticas te resbalen tu ponte lo quieras todo te queda hermoso y a las que no les gusta piña pues. Tu siempre seras la regia de regias. 😊😊😊👏👏👏👏👏👍💪💪💪💪🤩🤩🤩🥰🥰🥰🥰🥰",positive
9099,"YO NO ENTIENDO POR QUE LE DAN ACCIÓN DE OPINAR A ESTA C@G@D@ DE ABOGADUCHO, ESTE ES MÁS CORRUPTO QUE SU CLIENTE CACASTILLO… CHANCHOS DE LA MISMA BASURA💩🤬","YO NO ENTIENDO POR QUE LE DAN ACCIÓN DE OPINAR A ESTA C@G@D@ DE ABOGADUCHO, ESTE ES MÁS CORRUPTO QUE SU CLIENTE CACASTILLO… CHANCHOS DE LA MISMA BASURA💩🤬",negative
9431,"Si te queda mal hablan,si te queda bien hablan.Es@ssssss que de todo se fijan,pero no tienen espejo en su casa🙈😅 ILUS@SSSSS!!! Tu sigue limpiando nomas con tus vestidos😅 régios😍QUE TE QUEDAN CHEVERESSSSS😘😍OHHHHH MYYYYY,HE DICHO, CASO CERRADO🔫 upssss,no encontrava el martillo🙈😄😅😂😂😂😂","Si te queda mal hablan,si te queda bien hablan.Es@ssssss que de todo se fijan,pero no tienen espejo en su casa🙈😅 ILUS@SSSSS!!! Tu sigue limpiando nomas con tus vestidos😅 régios😍QUE TE QUEDAN CHEVERESSSSS😘😍OHHHHH MYYYYY,HE DICHO, CASO CERRADO🔫 upssss,no encontrava el martillo🙈😄😅😂😂😂😂",positive
9462,Eso fue trampa desde el inicio que casualidad que a Josimar lo hacen quedar el jurado con su cómodin cuando ya el público escogió a la uchulu en una eliminación contra el ...y ahora en una final el público no escoge al ganador si no el jurado 🙄eso es trampa ahí corre plata. No humildad ..Mi gan...,Eso fue trampa desde el inicio que casualidad que a Josimar lo hacen quedar el jurado con su cómodin cuando ya el público escogió a la uchulu en una eliminación contra el ...y ahora en una final el público no escoge al ganador si no el jurado 🙄eso es trampa ahí corre plata. No humildad ..Mi gana...,negative
9861,"😂😂😂increíble pero es cierto y Luisito Comunica lo sabe y lo dice porque lo vive,es difícil ser una figura pública y es verdad solo tomaron a esa chava pero no subieron cuantas veces solo.en ese lapso que pusieron los celulares en la cara y por más paciencia que un ser humano tenga se puede perd...","😂😂😂increíble pero es cierto y Luisito Comunica lo sabe y lo dice porque lo vive,es difícil ser una figura pública y es verdad solo tomaron a esa chava pero no subieron cuantas veces solo.en ese lapso que pusieron los celulares en la cara y por más paciencia que un ser humano tenga se puede perde...",negative
9894,Pero habla y piensa huevadas q al final recaerán en algún momento en los q tenemos hijos normales y gracias a esta estupida habrán tarados que les llega al huev... q distorsione el idioma y la forma de pensar de los niños . Pero a los q tenemos hijos y sabemos como criarlos nos jode q inviertan ...,Pero habla y piensa huevadas q al final recaerán en algún momento en los q tenemos hijos normales y gracias a esta estupida habrán tarados que les llega al huev... q distorsione el idioma y la forma de pensar de los niños . Pero a los q tenemos hijos y sabemos como criarlos nos jode q inviertan ...,negative
9990,Copia y pega esto para que les c@gues su publicación😁 ...,Copia y pega esto para que les c@gues su publicación😁,negative
10059,Primero el chifa p Toby jajaja y después su c@gu€ de risa y su chelitaaaaaaaa y todo tu pelada adentro 😜,Primero el chifa p Toby jajaja y después su c@gu€ de risa y su chelitaaaaaaaa y todo tu pelada adentro 😜,negative
10146,K@BR0N LA B3T0 XQ TE FUISTE A MÉXICO Si eres bien hombrecito quédate acá en PERÚ a enfrentar según tu al comunista de P.C. tu y tu banda los fujiburros están desesperados 👇👇😡😡😡,K@BR0N LA B3T0 XQ TE FUISTE A MÉXICO Si eres bien hombrecito quédate acá en PERÚ a enfrentar según tu al comunista de P.C. tu y tu banda los fujiburros están desesperados 👇👇😡😡😡,negative
10278,"Mis favoritasss y antes de salir siempre cheko sus videos esta vez quiero hacer la Ruta OYÓN(Lima)- YANAHUANCA(Pasco) (porque primero están las pozas termales que ya conozco pero me faltó conocer la ruta de las Lagunas como Patón, Guengue, Surasaca, Nevado Yarawuayna, Complejo Arqueológico de Ra...","Mis favoritasss y antes de salir siempre cheko sus videos esta vez quiero hacer la Ruta OYÓN(Lima)- YANAHUANCA(Pasco) (porque primero están las pozas termales que ya conozco pero me faltó conocer la ruta de las Lagunas como Patón, Guengue, Surasaca, Nevado Yarawuayna, Complejo Arqueológico de Ra...",neutral
10779,"Bienvenido a los comentarios, disfrute su recorrido: A la derecha estan los memes; a la izquierda los comentarios que no tienen que ver con la publicacion, al final del pasillo los religiosos acompañados de las cadenas que dicen ""Si no mandas esto a X numero de personas moriras..."" Al lado esta ...","Bienvenido a los comentarios, disfrute su recorrido: A la derecha estan los memes; a la izquierda los comentarios que no tienen que ver con la publicacion, al final del pasillo los religiosos acompañados de las cadenas que dicen ""Si no mandas esto a X numero de personas moriras..."" Al lado esta ...",negative
11067,"Casi imposible creer que esta generación z del Bicentenario con tanta tecnología a la mano y tanta información hayan creído que ese N@riz©n era la salvación del Perú, el padre de todos, Cuando el Sinvergüenza está que se levantaba en peso al Perú entero.","Casi imposible creer que esta generación z del Bicentenario con tanta tecnología a la mano y tanta información hayan creído que ese N@riz©n era la salvación del Perú, el padre de todos, Cuando el Sinvergüenza está que se levantaba en peso al Perú entero.",negative
11145,"Linda María Pia, te queda espectacular el vestido, y l@s que tanto rajaron, es porque a nadie le va a quedar tan bien como a tí, sigue con los éxitos y muchas bendiciones para ti 🤗","Linda María Pia, te queda espectacular el vestido, y l@s que tanto rajaron, es porque a nadie le va a quedar tan bien como a tí, sigue con los éxitos y muchas bendiciones para ti 🤗",positive
12314,"¶Hace 45 años, nuestro 🇵🇪 *PERÚ*🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Fujimori"" con su siamés y secuas el criminal y delincuente arequipeño Ex agente de la CIA JudíoEstadounidense ...","¶Hace 45 años, nuestro 🇵🇪 *PERÚ*🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Fujimori"" con su siamés y secuas el criminal y delincuente arequipeño Ex agente de la CIA JudíoEstadounidense V...",negative

In [8]:
import re

patron_mencion_real = r"(?<!\w)@\w+"   # @ NO precedido por una letra/número/guion_bajo

con_mencion["es_mencion_real"] = con_mencion["text_clean"].str.contains(patron_mencion_real, regex=True, na=False)

print("Menciones reales (usuario/persona):", con_mencion["es_mencion_real"].sum())
print("Uso de @ como letra dentro de palabra (censura/lenguaje inclusivo):", (~con_mencion["es_mencion_real"]).sum())

con_mencion[con_mencion["es_mencion_real"]][["text_clean", "label_name"]]

Menciones reales (usuario/persona): 24
Uso de @ como letra dentro de palabra (censura/lenguaje inclusivo): 32

/tmp/ipykernel_2470/560871147.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  con_mencion["es_mencion_real"] = con_mencion["text_clean"].str.contains(patron_mencion_real, regex=True, na=False)

,text_clean,label_name
28,"Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto",negative
1029,"¶Hace 45 años, nuestro 🇵🇪PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA JudíoEs...",negative
3376,"Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total",negative
3456,"Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻",neutral
3687,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,positive
4260,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,negative
4731,"Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! MASMUSICACONMARSHALL in one 🌎",positive
4957,"Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍",positive
5510,@Un tombo pasó por ahí en una moto deportiva 🤣,neutral
5670,"Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una reconoc...",negative
5928,@asistenciaestudioespinozaramos ya fuiste 🤣🤣🤣,negative
7070,"Aaayyyy por Dios cómo se llenan la boca atacando la, quien sabe cómo fue su infancia y como superó todas las trabas que te pone la vida al no ser comprendida, nadie sabe, pero lo superó y ahora busca ayuda para con sus hijos y quién mejor que ella saber cómo ayudar a sus pequeños porque lamentab...",negative
7096,Todo el PERU esta contigo @smulanovich 🇵🇪 Las redes de la corrupcion llegan a todos lados 😡 No te dejes pisar el poncho 💪,negative
7805,Quisiera ganarla porque mi novio le encanta el fútbol es un jugadorazo pero de fútbol eh jejeje sería un lindo regalo para el participen amigos de este lindo premio te sigo como @med141923 Jorge Teves Taipe Mica Isabel Castillo Elena Lizárraga Con mucha fe bendiciones 😘,positive
8759,"Yo tengo que ganarme ese Canguro si o si , siganme para más recetas Huaralinas 😅😝❤️ @lahuaralina.pe",positive
8947,"Muy bien @Maria Pia Copello, te felicito que las criticas te resbalen tu ponte lo quieras todo te queda hermoso y a las que no les gusta piña pues. Tu siempre seras la regia de regias. 😊😊😊👏👏👏👏👏👍💪💪💪💪🤩🤩🤩🥰🥰🥰🥰🥰",positive
9462,Eso fue trampa desde el inicio que casualidad que a Josimar lo hacen quedar el jurado con su cómodin cuando ya el público escogió a la uchulu en una eliminación contra el ...y ahora en una final el público no escoge al ganador si no el jurado 🙄eso es trampa ahí corre plata. No humildad ..Mi gana...,negative
10278,"Mis favoritasss y antes de salir siempre cheko sus videos esta vez quiero hacer la Ruta OYÓN(Lima)- YANAHUANCA(Pasco) (porque primero están las pozas termales que ya conozco pero me faltó conocer la ruta de las Lagunas como Patón, Guengue, Surasaca, Nevado Yarawuayna, Complejo Arqueológico de Ra...",neutral
12314,"¶Hace 45 años, nuestro 🇵🇪 *PERÚ*🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Fujimori"" con su siamés y secuas el criminal y delincuente arequipeño Ex agente de la CIA JudíoEstadounidense V...",negative
12323,Excelente video Kari😊😊 todos se ven súper prácticos pero me encantó la OmeletteMaker BlanikPeru para hacer diferentes combinaciones y así los chicos disfruten de un nutritivo desayuno😋😋 YoQuieroMiBlanik🙋🙋te sigo en IG como @sarytahuaman😘😘,positive
13489,@Sofia Aguero JAJA NOSOTRAS en los quinos😂😍,neutral
13516,"Oe que mrd yo he entrado para ver a ala rata perder su plata y cancelar retiro, que es esta hu€\/@da 🤢🤮😡",negative
13826,Exiliado???? ©orriste.... Y quedate ahi .... aprende a hacer periodista y a ser imparcial ...por eso estas ahi ... si eres tan buen periodista... porqué no tienes chamba ahi ..como Laura Bozzo....saben porque?...porque ya saben el historial y ahi en ese pais te van a ¶estruir...por eso Willax te...,negative
14251,"Mi admiración y respeto a nuestra deportista Sofia Mulanovich @smulanovich, quien siempre ha dejado en alto a nuestro país 🇵🇪. El Centro de Arbitraje Deportivo no está activado, siendo parte del Comité Olímpico Peruano @COP_Peru, ayudaría mucho en estos casos y la Federación también tendría la o...",neutral

In [9]:
def anonimizar_menciones_reales(text):
    return re.sub(r"(?<!\w)@\w+", "@usuario", text)

df_clean["text_clean"] = df_clean["text_clean"].apply(anonimizar_menciones_reales)

# Verificación
patron_mencion_real = r"(?<!\w)@\w+(?<!@usuario)"
quedan = df_clean["text_clean"].str.contains(r"(?<!\w)@(?!usuario\b)\w+", regex=True, na=False).sum()
print("Menciones reales sin anonimizar restantes:", quedan)
print("Ejemplos de texto ya anonimizado:")
df_clean[df_clean["text_clean"].str.contains("@usuario", regex=False, na=False)][["text", "text_clean"]].head(10)

Menciones reales sin anonimizar restantes: 0
Ejemplos de texto ya anonimizado:

,text,text_clean
28,"Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@o🥴🥴🥴 y no tiene para pagar su cuarto","Chino dile a ese pelado que se deje de estarme pidiendo CANJE , como tiene para chupar como pendej@@usuario🥴🥴🥴 y no tiene para pagar su cuarto"
1029,"¶Hace 45 años, nuestro 🇵🇪#PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA Judí...","¶Hace 45 años, nuestro 🇵🇪PERÚ🇵🇪 desde Morales Bermúdes, pasando por Belaunde Terry, seguido por García Pérez; luego el hampón y genocida Japonés el Yakuza Kenya Inami Inamoto alias ""Alberto Fujimori"" con su siamés y secuas el criminal, delincuente y traídor arequipeño Ex agente de la CIA JudíoEs..."
3376,"Videaso, que tales monstruos!!! Todos a las @wsl carajo!!! 🙌 respect total","Videaso, que tales monstruos!!! Todos a las @usuario carajo!!! 🙌 respect total"
3456,"Luciano, tienes que pasar por el @Palacio del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻","Luciano, tienes que pasar por el @usuario del Sancochado Av. 28 de julio 990 - Cercado. También el Rinconcito Ferreñafano (frente al Congreso). Por el arroz con pato con ceviche de entrada 🙌🏻"
3687,❤️Vamos. Michi @micheilleSoifer si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma,❤️Vamos. Michi @usuario si se puede estoy segura q vas a seguir en competencia yo te lo aseguro un saludo muy grande desde la. Ciudad de Casma
4260,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es #Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@Niurka,Quieren hacer Fraude Televisa y La Casa de los Famosos México Están protegiendo a su consentido !! Esto ya es Viral Fuera Poul) Fueraaaa!! 😤😤😤😤😤😤 Sergio Mayer Breton @ Emilio !!! Que Mexico alce la Voz💢💢💢💢💢💢@usuario
4731,"Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @joaboloña la rubia hermosa...cuídense besos! #MASMUSICACONMARSHALL in one 🌎","Saludos chicas , sería excelente ganar ese parlante de la gran industria de sonido Marshall debe sonar fabuloso ojalá tenga la suerte con @usuario la rubia hermosa...cuídense besos! MASMUSICACONMARSHALL in one 🌎"
4957,"Muy bien, @Gerardo Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍","Muy bien, @usuario Pe' da gusto cuando lo pones punche sigue así estuvo entretenido tienes un like 👍"
5510,@Un tombo pasó por ahí en una moto deportiva 🤣,@usuario tombo pasó por ahí en una moto deportiva 🤣
5670,"Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de #Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una rec...","Lo de ese asqueroso de Richard swing debe sancionarse si o si, pero no sean pendejos, en otros lados siempre hacían lo mismo y nadie decía nada...pero, Deplorable lo de Swing, pero vomitivo que lo condene carla garcia... la hija del ex-Presidente que contrató (de pura 🔥calentura 🔥) a una reconoc..."

## Verificar textos vacios

In [10]:
# Revisar textos vacíos tras la limpieza
vacios = df_clean[
    df_clean["text_clean"].isna() | (df_clean["text_clean"].astype(str).str.strip() == "")
]
print("Textos vacíos tras limpieza:", len(vacios))

# Revisar textos muy cortos (menos de 3 caracteres) como señal de alerta
muy_cortos = df_clean[df_clean["text_clean"].astype(str).str.len() < 3]
print("Textos con menos de 3 caracteres tras limpieza:", len(muy_cortos))
muy_cortos[["text", "text_clean", "label_name"]]

Textos vacíos tras limpieza: 0
Textos con menos de 3 caracteres tras limpieza: 0

Empty DataFrame
Columns: [text, text_clean, label_name]
Index: []

In [11]:
# Verificación final: nulos, duplicados en text_clean, y distribución de clases
print("Nulos por columna:")
print(df_clean.isnull().sum())

print("\nDuplicados en text_clean (pueden aparecer si dos textos distintos quedan iguales tras limpiar):")
duplicados_text_clean = df_clean["text_clean"].duplicated().sum()
print(duplicados_text_clean)

print("\nDistribución de clases en el pool limpio:")
print(df_clean["label_name"].value_counts())
print((df_clean["label_name"].value_counts(normalize=True) * 100).round(2))

print("\nTotal de registros en el pool limpio final:", len(df_clean))

Nulos por columna:
text              0
label             0
label_name        0
split_original    0
text_clean        0
dtype: int64

Duplicados en text_clean (pueden aparecer si dos textos distintos quedan iguales tras limpiar):
0

Distribución de clases en el pool limpio:
label_name
negative    6636
positive    4732
neutral     3176
Name: count, dtype: int64
label_name
negative    45.63
positive    32.54
neutral     21.84
Name: proportion, dtype: float64

Total de registros en el pool limpio final: 14544

In [12]:
# Guardamos el pool limpio final (antes del split 80/10/10)
df_clean_final = df_clean[["text", "text_clean", "label", "label_name"]].copy()

df_clean_final.to_csv("smps_clean_pool.csv", index=False)
df_clean_final.to_parquet("smps_clean_pool.parquet", index=False)

print("Guardado. Total de registros en el pool limpio final:", len(df_clean_final))

Guardado. Total de registros en el pool limpio final: 14544